config/routes.rb
Rails.application.routes.draw do
  resources :users, :blogs

  root 'home_page#home'
  get '/home' => 'home_page#home'

  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

	before_save { email.downcase! }

	EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :username, :presence => true, uniqueness: { case_sensitive: false } , :length => { :in => 4..30 }
	validates :email, :presence => true, uniqueness: { case_sensitive: false }, :format => EMAIL_REGEX
	validates :password, length: { minimum: 6 } 
	has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
    print Time.now
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :published_date, :author)
    end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController

	def home
		@user = User.new
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/users_helper.rb
module UsersHelper

	#add gravatar image as a user's profile image
	def user_gravatar(user)		
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, class: "gravatar")
	end
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title %>
    <div class="controls">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :body, :class=>"control-group" %>
    <div class="controls">
      <%= f.text_area :body %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :published_date, :class=>"control-label" %>
    <div class="controls">
      <%= f.datetime_select :published_date %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :author, :class=>"control-label" %>
    <div class="controls">
      <%= f.text_field :author, :class=>"some-class", :value=>"Rabi" %>
    </div>
  </div>
  <div class="control-group">
    <%= select_tag(:city_id, options_for_select([['Lisbon', 1], ['Madrid', 2]])) %>    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<div class="span9">
  <h2>Listing blogs</h2>

  <table class="table table-bordered">
    <caption>Table listing all the blogs</caption>
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th>Published date</th>
        <th>Author</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @blogs.each do |blog| %>
        <tr>
          <td><%= blog.title %></td>
          <td><%= blog.body %></td>
          <td><%= blog.published_date %></td>
          <td><%= blog.author %></td>
          <td><buttton type="button" class="btn btn-small btn-info"><%= link_to 'Show', blog %></buttton></td>
          <td><buttton type="button" class="btn btn-small"><%= link_to 'Edit', edit_blog_path(blog) %></buttton></td>
          <td><buttton type="button" class="btn btn-small btn-danger"><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></buttton></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Blog', new_blog_path %>
</div>   

<div class="span3">
  <h2> Some sidebar</h2>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </p>
</div>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<div class="span9">
	<p id="notice"><%= notice %></p>

	<p>
	  <h3><strong><%= @blog.title %></strong></h3>
	  <small>Author: <%= @blog.author %></small>
		<small>Published date: <%= @blog.published_date %></small>
	</p>


	<p class="blog_body">
	  <%= @blog.body %>
	</p>

	<%= link_to 'Edit', edit_blog_path(@blog) %> |
	<%= link_to 'Back', blogs_path %>
</div>

app/views/home_page/home.html.erb
<div class="span12">
	<div class="center hero-unit">
		<h2>Welcome to the blog site. This is a simple site created as an attempt to learn 'Ruby on Rails'</h2>
		<em>The following button is suppose to show signup form once it is clicked</em><br>
		<button id="signup" class="btn btn-large btn-primary" data-click = "0" type="button">Signup</button>
		
		<div id="signup_form" class="row-fluid">
		
		</div>
		
		<script type="text/javascript">
			var signup = document.getElementById("signup");
			var signup_form = document.getElementById("signup_form");
			var form = '<%= escape_javascript render :partial => 'users/form' %>';
			var form_element;

			signup.addEventListener("click", function(){
				
				if(signup.dataset.click === "0"){
					signup_form.innerHTML = form;
					signup.dataset.click = 1;				
				}
				else{
					signup_form.innerHTML = "";
					signup.dataset.click = 0;
				}


			});
		</script>
	</div>
</div>

app/views/layouts/_navbar.html.erb
 
<div class="navbar">
	<div class="navbar-inner">  		
	    <ul class="nav">
	    	<a href="/home" class="brand"><%= image_tag "home.png", :class => "logoicon" %></a>
	    	<li>
	    		<a href="/home">Home</a>
	  		</li>
	    	<li><a href="/blogs"> Blogs </a></li>
	    	<li><a href="/users"> Users </a></li>
	    </ul>
	</div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewRailsApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<div class="container-fluid">
		<div class="page-header">
    		<h1>Simple Rails App <small>kind of a blog site</small></h1>
    	</div>    	
    	<%= render 'layouts/navbar' %>

	
		<div class="row-fluid">
    		<%= yield %>
    	</div>
    </div>    
</body>
</html>

app/views/layouts/home_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewRailsApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<div class="page-header logo_motto">
		<h1>Simple Rails App <small>kind of a blog site</small></h1>
	</div>
	<div class="container-fluid">

	    <div class="row-fluid">
	    	<%= yield %>
	    </div>
    </div>

</body>
</html>

app/views/shared/_error_message.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>  
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="span4 centered_form">
  <%= simple_form_for(@user) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= render 'shared/error_message' %>
      <%= f.input :username, :placeholder => 'ex- john doe', :validate => true %>
      <%= f.input :email, :placeholder => 'ex- john.doe@johndoe.com', :validate => true %>
      <%= f.input :password, as: :password, :validate => true %>
      <%= f.input :password_confirmation, as: :password, :validate => true %>
    </div>
      <%= f.button :submit, :value => 'Create Account' %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="span9">
	<h2>Editing user</h2>

	<%= render 'form' %>

	<%= link_to 'Show', @user %> |
	<%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<div class="span9">
  <h2>Listing users</h2>

  <table class="table table-bordered">
    <caption>Table listing all the blogs</caption>
  <thead>
    <tr>
      <th>S.N</th>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3">Acitons</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>

  <br>

  <%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="span9">
	<div class="span3">
		<%= user_gravatar @user %>
	</div>
	<div class="span6">
		<%= @user.username %>
	</div>

	<% #link_to 'Edit', edit_user_path(@user) %>
	<% #link_to 'Back', users_path %>
</div>
<div class="span12">
<h2> Your blog posts </h2>
</div>